<?php
/**
 * ContacteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

namespace OH\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;


class ContacteRepository extends EntityRepository
{
}
